---
# http://www.rabbithacks.com/esp8266/esp12-e-directly-usable-gpio-pins/

#RST: 1
#ADC: 2
#TOUT: 2
#EN: 3
#CHPD: 3
WAKE: GPIO16
HSPI_CLK: GPIO14
HSPI_Q: GPIO12
HSPI_D: GPIO13
CTS0: GPIO13
RXD2: GPIO13

# SD_CMD: 9
# MOSI: 9
# SD_D0: 10
# MISO: 10
SD_D2: GPIO9
SD_D3: GPIO10
CS: GPIO10
# SD_D1: 13
# INT: 13
# SD_CLK: 14
# CLK: 14
# GND: 15
TXD2: GPIO15
RTS0: GPIO15 
HSPI_CS: GPIO15
TXD1: GPIO2
CS2: GPIO0
RXDO: GPIO3
TXD0: GPIO1
CS1: GPIO1
