---
# https://esphome.io/components/switch/gpio.html

platform: gpio
  pin: GPIO0
  name: "${upper_devicename} GPIO0"
platform: gpio
  pin: GPIO2
  name: "${upper_devicename} GPIO2"
  
# - platform: gpio
  # pin: GPIO4
  # name: "${upper_devicename} GPIO4"
  
# - platform: gpio
  # pin: GPIO5
  # name: "${upper_devicename} GPIO5"
  
# - platform: gpio
  # pin: GPIO12
  # name: "${upper_devicename} GPIO12"
  
# - platform: gpio
  # pin: GPIO13
  # name: "${upper_devicename} GPIO13"
  
# - platform: gpio
  # pin: GPIO14
  # name: "${upper_devicename} GPIO14"
  
# #  - platform: gpio
# #      pin: GPIO15
# #      name: "${upper_devicename} GPIO15"

# - platform: gpio
  # pin: GPIO16
  # name: "${upper_devicename} GPIO16"
